apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdms-client
  namespace: boreholes
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: 'true'
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdms-client
  template:
    metadata:
      labels:
        app: bdms-client
    spec:
      containers:
      - name: bdms-client
        image: ghcr.io/geoadmin/suite-bdms-client:edge
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
          - name: TZ
            valueFrom:
              secretKeyRef:
                name: boreholes
                key: TZ
