apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-legacy
  namespace: {{ .Release.Namespace }}
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: 'true'
    keel.sh/trigger: poll
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-legacy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api-legacy
    spec:
      containers:
        - name: {{ .Release.Name }}-api-legacy
          image: ghcr.io/geoadmin/suite-bdms-api-legacy:{{ .Values.app.version | default "latest" }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: databaseHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: databasePort
                  optional: true
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: databaseName
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: databaseUsername
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: databasePassword
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: timezone
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-legacy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-api-legacy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
