apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  namespace: {{ .Release.Namespace }}
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: 'true'
    keel.sh/trigger: poll
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-client
    spec:
      containers:
        - name: {{ .Release.Name }}-client
          image: ghcr.io/geoadmin/suite-bdms-client:{{ .Values.app.version | default "latest" }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: timezone
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

