apiVersion: v1
kind: Secret
metadata:
  name: boreholes
  namespace: boreholes
type: Opaque
stringData:
  # ------------------------------------------------------------------------- #
  # The fully qualified base domain name used for all pods                    #
  # ------------------------------------------------------------------------- #
  BASE_DOMAIN: example.com

  # ------------------------------------------------------------------------- #
  # PostgreSQL database configuration                                         #
  # ------------------------------------------------------------------------- #
  DB_HOST:
  #DB_PORT: '5432' #optional
  DB_DATABASE:
  DB_USERNAME:
  DB_PASSWORD:

  # ------------------------------------------------------------------------- #
  # The PostgreSQL DB connection string for the .NET REST API (v2)            #
  # using the following schema:                                               #
  # `Host=my_host[:port];Database=my_db;Username=my_user;Password=my_pw`      #
  # ------------------------------------------------------------------------- #
  DB_CONNECTIONSTRING:

  # ------------------------------------------------------------------------- #
  # The legacy python API to proxy /api/v1 requests to                        #
  # ------------------------------------------------------------------------- #
  LEGACY_API_ENDPOINT: http://bdms-api-legacy.boreholes.svc.cluster.local

  # ------------------------------------------------------------------------- #
  # AWS S3 Bucket configuration (borehole attachments)                        #
  # ------------------------------------------------------------------------- #
  S3_ENDPOINT: https://s3.eu-central-1.amazonaws.com
  S3_BUCKET_NAME:
  #S3_ACCESS_KEY: #optional, default IAM
  #S3_SECRET_KEY: #optional, default IAM
  #S3_SECURE: '1' #optional, default uses a secure TLS connection

  # ------------------------------------------------------------------------- #
  # OpenID Connect configuration                                              #
  # ------------------------------------------------------------------------- #
  AUTH_AUTHORITY:
  AUTH_AUDIENCE:
  AUTH_SCOPES: "openid profile"
  AUTH_GROUP_CLAIM_TYPE:
  AUTH_AUTHORIZED_GROUP_NAME:

  # ------------------------------------------------------------------------- #
  # The default timezone to use for all containers                            #
  # ------------------------------------------------------------------------- #
  TZ: Europe/Zurich
